### GET request to example server
GET https://nebuladrift-c244d-default-rtdb.firebaseio.com/users/-O8Vw-9IKfW760X21Ebs.json
Accept: application/json
### Response


### POST request to example server
POST https://nebuladrift-c244d-default-rtdb.firebaseio.com/users.json
Accept: application/json
Content-Type: application/json

{
  "username": "johndoe",
  "name": "John Doe"
}
